version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    volumes: 
      - 'database:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes: 
  database: 
