spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mypet}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:secret}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
