spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:ucode}
    password: ${DB_PASS:secret}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  security:
    cors:
      origin: "*"
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.asgardeo.io/t/mypet/oauth2/token 
          jwk-set-uri: https://api.asgardeo.io/t/mypet/oauth2/jwks
    jwt:
      publicKey: classpath:publicKey
      privateKey: classpath:privateKey
  devtools:
    livereload.enabled: false
